#!/bin/bash
#### CA Portion ####

## Creating a key for the CA (Certificate Authority)
#openssl genrsa -des3 -out ca.key 4096, adding passphrase
openssl genrsa -out ca.key 4096

## Create a CA Certificate
#openssl req -new -nodes -x509 -days 365 -key ca.key -out ca.crt
#openssl x509 -in ca.crt -text -noout, content of the certificate
openssl req -new -nodes -x509 -days 365 -key ca.key -out ca.crt -subj "/C=IL/L=Jer/O=CA"


#### Server Cert ####

## Create the Server Key
openssl genrsa -out nginx_server.key 2048

## Create The Server CSR (Certificate Signing Request)
#openssl req -in nginx_server.csr -noout -text, content of the CSR
openssl req -new -key nginx_server.key -out nginx_server.csr -subj "/C=IL/L=Jer/O=NginX"

## Create The Server Cert
#openssl x509 -in nginx_server.crt -text -noout
openssl x509 -req -days 730 -in nginx_server.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out nginx_server.crt

## Creating a PKCS
openssl pkcs12 -export -out server.pfx -inkey nginx_server.key -in nginx_server.crt -certfile ca.crt -password pass:1


#### Client Cert ####

## Create a user key
openssl genrsa -out user.key 2048

## Create a user CSR (Certificate Signing Request)
openssl req -new -key user.key -out user.csr -subj "/C=IL/L=Jer/O=UserCert"

## Signing the CSR and creating the user cert
openssl x509 -req -days 365 -in user.csr -CA ca.crt -CAkey ca.key -set_serial 01 -out user.crt

## Creating a PKCS
openssl pkcs12 -export -out user.pfx -inkey user.key -in user.crt -certfile ca.crt -password pass:12


#### Moving CA Cert, Server Cert and Key to Where Nginx is Looking for them ####
mv nginx_server.crt /etc/ssl/certs/nginx_server.crt
mv nginx_server.key /etc/ssl/private/nginx_server.key
mv ca.crt /etc/ssl/certs/ca.crt


#### Moving PKCS to where one can download from, also for that purpose granting permission to the user ubuntu
mkdir /home/ubuntu/PKCS/

mv server.pfx /home/ubuntu/PKCS/server.pfx
chown root:ubuntu /home/ubuntu/PKCS/server.pfx
chmod 640 /home/ubuntu/PKCS/server.pfx

mv user.pfx /home/ubuntu/PKCS/user.pfx
chown root:ubuntu /home/ubuntu/PKCS/user.pfx
chmod 640 /home/ubuntu/PKCS/user.pfx


#### Didn't really understand what is this for #### Link https://www.digitalocean.com/community/tutorials/how-to-create-a-self-signed-ssl-certificate-for-nginx-in-ubuntu-16-04
sudo openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048
