#!/bin/bash

## Server Cert ##
# Create the Certificate
sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt

# Create Diffie-Hellman Group
sudo openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048

## Client Cert ##
# Creating a key for the CA (Certificate Authority)
openssl genrsa -des3 -out ca.key 4096

# Create a CA Certificate
openssl req -new -x509 -days 365 -key ca.key -out ca.crt

# Create a key for the user
openssl genrsa -des3 -out user.key 4096

# Create a CSR (Certificate Signing Request)
openssl req -new -key user.key -out user.csr

# Signing the CSR
openssl x509 -req -days 365 -in user.csr -CA ca.crt -CAkey ca.key -set_serial 01 -out user.crt

# Creating a PKCS
openssl pkcs12 -export -out user.pfx -inkey user.key -in user.crt -certfile ca.crt
