version: '2'

services:  
  drupal:
    build:
      context: .
      dockerfile: Dockerfile.drupal
    container_name: drupal
    image: custom-drupal
    ports: ["8080:80"]
    volumes:
      - drupal_modules:/var/www/html/modules
      - drupal_profiles:/var/www/html/profiles
      - drupal_sites:/var/www/html/sites
      - drupal_themes:/path/on/host/themes

  postgres:
    container_name: postgres
    image: postgres:12.1
    environment:
      POSTGRES_PASSWORD: "123"
    volumes:
      - drupal-data:/var/lib/postgresql/data

volumes:
  drupal_modules:
  drupal_profiles:
  drupal_sites:
  drupal_themes:

  drupal-data:


#volumes: # Optional, same as docker volume create

#networks: # Optional, same as docker network create