#!/bin/bash

source ./vars_file

## installing wordpress 
# download wordpress 
cd /tmp
curl -O https://wordpress.org/latest.tar.gz
tar xzvf latest.tar.gz

# create empty htaccess file
touch /tmp/wordpress/.htaccess

# create wordpress config file out of the template
cp /tmp/wordpress/wp-config-sample.php /tmp/wordpress/wp-config.php

# to allow wordpress in the future make upgrades on its own
mkdir /tmp/wordpress/wp-content/upgrade

cp -a /tmp/wordpress/. /var/www/$apache_site_domain_name
cp -a /tmp/wordpress/. /var/www/html

## adjust permissions
chown -R www-data:www-data /var/www/html
chown -R www-data:www-data /var/www/$apache_site_domain_name

find /var/www/$apache_site_domain_name/ -type d -exec chmod 750 {} \;
find /var/www/$apache_site_domain_name/ -type f -exec chmod 640 {} \;

find /var/www/html/ -type d -exec chmod 750 {} \;
find /var/www/html/ -type f -exec chmod 640 {} \;

curl -s https://api.wordpress.org/secret-key/1.1/salt/ > temp_data_file

/var/www/$apache_site_domain_name/wp-config.php

sed -i '49,56d' /var/www/$apache_site_domain_name/wp-config.php
sed "49r temp_data_file" /var/www/$apache_site_domain_name/wp-config.php

rm -rf temp_data_file
