#!/bin/bash

## set the following to able to depekeg without interactive answering
export DEBIAN_FRONTEND=noninteractive
debconf-set-selections <<< 'mysql-apt-config        mysql-apt-config/repo-distro    select  ubuntu'
debconf-set-selections <<< 'mysql-apt-config        mysql-apt-config/select-product select  Ok'
debconf-set-selections <<< 'mysql-apt-config        mysql-apt-config/repo-url       string  http://repo.mysql.com/apt'
debconf-set-selections <<< 'mysql-apt-config        mysql-apt-config/tools-component        string  mysql-tools'
debconf-set-selections <<< 'mysql-apt-config        mysql-apt-config/select-tools   select  Enabled'
debconf-set-selections <<< 'mysql-apt-config        mysql-apt-config/select-server  select  mysql-8.0'
debconf-set-selections <<< 'mysql-apt-config        mysql-apt-config/dmr-warning    note'
debconf-set-selections <<< 'mysql-apt-config        mysql-apt-config/repo-codename  select  bionic'
debconf-set-selections <<< 'mysql-apt-config        mysql-apt-config/unsupported-platform   select  abort'
debconf-set-selections <<< 'mysql-apt-config        mysql-apt-config/preview-component      string'
debconf-set-selections <<< 'mysql-apt-config        mysql-apt-config/select-preview select  Disabled'

## downloading the package and installing it ##
curl -OL https://dev.mysql.com/get/mysql-apt-config_0.8.13-1_all.deb
dpkg -i mysql-apt-config*
rm -rf mysql-apt-config*

## update and install mysql client ##
apt update -y
apt install mysql-client -y