#!/bin/bash
# Defining Vars
# Repo Paths
Github_Repo_Parent="https://github.com/L1nuxProdigy/LinuxLabs"
Nginx_Project_Path="/Nginx/Assignment_A/Public_Domain_Implementation/"

#In the Remote Machine Paths
Temp_Folder="/home/ubuntu/Temp"
Project_Folder="/home/ubuntu/nginx-terraform-repo"
Terraform_Project_Folder=$Project_Folder/Terraform_Deploy
Github_Copied_Location=$Temp_Folder/$Nginx_Project_Path


#Script to pull the git files to the terraform machine
mkdir $Temp_Folder
cd $Temp_Folder
git init
git remote add origin -f $Github_Repo_Parent
git config core.sparseCheckout true
echo $Nginx_Project_Path > .git/info/sparse-checkout
git pull origin master

mkdir $Project_Folder
mv $Github_Copied_Location/* $Project_Folder

rm -rf $Temp_Folder
cd $Terraform_Project_Folder

#Calling the Script for configuring terraform
./Terraform_Aggregate_Script