#!/bin/bash
source ./Bash_Vars_for_Terraform

#installing Terraform
apt update
apt install unzip
wget https://releases.hashicorp.com/terraform/0.12.8/terraform_0.12.8_linux_amd64.zip
unzip ./terraform_0.12.8_linux_amd64.zip
mv ./terraform /usr/local/bin/
rm -rf ./terraform_0.12.8_linux_amd64.zip
chown ubuntu /usr/local/bin/

cd $Terraform_Project_Folder
terraform init


